---
downloads: ~/.ansible-downloads/

configure_dotfiles: false
configure_terminal: true
configure_osx: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove: []
 - Launchpad
 - TV
 - Podcasts
 - 'App Store'
# dockitems_persist: []
# - name: "Sublime Text"
#   path: "/Applications/Sublime Text.app/"
#   pos: 5

configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

# dotfiles_repo: https://github.com/carlseverson/dotfiles
# dotfiles_repo_accept_hostkey: true
# dotfiles_repo_local_destination: ~/
# dotfiles_files:
#   - .zshrc
#   - .gitignore
#   - .osx


homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - ack
  - autoconf
  - awscli
  - brotli
  - c-ares
  - ca-certificates
  - cffi 
  - docutils
  - gettext
  - git
  - httpie
  - icu4c
  - libnghttp2
  - libuv
  - libzip
  - lz4
  - m4
  - mpdecimal
  - node
  - nvm
  - nmap
  - openssl
  - pcre2
  - pkg-config
  - pycparser
  - pyenv
  - python@3.11
  - r
  - readline
  - six 
  - sqlite
  - tldr
  - tree
  - wget
  - xz
  - zstd

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - anaconda
  - anki
  - audacity 
  - backblaze
  - beekeeper-studio
  - bitwarden
  - brave-browser
  - calibre
  - cheatsheet
  - citrix-workspace
  - discord
  - docker
  - firefox
  - google-chrome
  - imageoptim
  - iterm2
  - jellyfin
  - jellyfin-media-player
  - libreoffice
  - maccy
  - papers
  - qlcolorcode
  - qlmarkdown
  - qlprettypath
  - qlstephen
  - quicklook-csv
  - quicklook-json
  - rectangle
  - signal
  - slack
  - sublime-text
  - superduper
  - suspicious-package
  - transmission
  - visual-studio-code
  - vmware-horizon-client
  - webpquicklook
  - zoom
  


# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.

npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Set to 'true' to configure Sublime Text.
configure_sublime: false
sublime_base_path: '~/Library/Application Support/Sublime Text'
sublime_config_path: "Packages/User"
sublime_package_control:
  - "DocBlockr"
  - "Dockerfile Syntax Highlighting"
  - "FileDiffs"
  - "GitHub Flavored Markdown Preview"
  - "Jinja2"
  - "Package Control"
  - "PHP-Twig"
  - "Pretty JSON"
  - "SublimeLinter"
  - "SublimeLinter-contrib-yamllint"
  - "TrailingSpaces"
  - "WordCount"

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
